### ISSUE TITLE
按照您的文档，转完onnx后，运行的时候报错

### ISSUE THREAD

**Issue by xunxuntu** [Shaohu-Li/Onnx-TensorRT-Python#1]
您好，我按照您的方式来导出和运行，下面是我的操作流程，
```
# 导出onnx
# 在yolov7目录下导出onnx
python export.py --weights weights/yolov7-tiny.pt --grid  --simplify

# 运行
(Onnx-TensorRT-Python) root@1050:/home/simple/my_desktop/Onnx-TensorRT-Python/Onnx-TensorRT-Python-master# python export_TRT.py -o weights/yolov7-tiny.onnx -e weights/yolov7-tiny.onnx


报错：
Namespace(conf_thres=0.4, end2end=False, engine='weights/yolov7-tiny.onnx', img_path='src/video1.mp4', iou_thres=0.5, mode='video', onnx='weights/yolov7-tiny.onnx', precision='fp32', scores_thres=0.25)
Loading TRT fil from : /home/simple/my_desktop/Onnx-TensorRT-Python/Onnx-TensorRT-Python-master/weights/yolov7-tiny.onnx
=======engine_file_path: /home/simple/my_desktop/Onnx-TensorRT-Python/Onnx-TensorRT-Python-master/weights/yolov7-tiny.onnx
[08/19/2023-13:55:46] [TRT] [E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
======engine: None
Traceback (most recent call last):
  File "export_TRT.py", line 542, in <module>
    trt_model = TRT(args.onnx, args.engine, args.precision, args.end2end, args.conf_thres, args.iou_thres, args.scores_thres)
  File "export_TRT.py", line 50, in __init__
    self.Init_model()
  File "export_TRT.py", line 62, in Init_model
    self.engine = self.readTrtFile(self.engine_file_path)
  File "export_TRT.py", line 412, in readTrtFile
    assert engine, "反序列化之后的 engine 为空，确保转换过程的正确性。 "
AssertionError: 反序列化之后的 engine 为空，确保转换过程的正确性。


```

![image](https://github.com/Shaohu-Li/Onnx-TensorRT-Python/assets/134046837/719b9d2f-724f-481a-821e-70e9431de340)

**Comment by xunxuntu** [comment]
我的 trt版本的是7.0.0.11  cudnn版本7.6.5 cuda 版本是10.2

**Comment by ssunchaser** [comment]
谢谢您提出的问题，最后的命令应该为 ： python export_TRT.py -o weights/yolov7-tiny.onnx -e weights/yolov7-tiny.trt。应该是我这边上传的时候忘记更改了，您可以再次尝试一下看看。

**Comment by xunxuntu** [comment]
请问这个yolov7-tiny.trt是怎么来的呀，是通过什么方式得到的

**Comment by xunxuntu** [comment]
![image](https://github.com/Shaohu-Li/Onnx-TensorRT-Python/assets/134046837/60bb79f6-e47c-45ff-a937-0d8872bfbbc4)

engine 能正确转换了，但是报了一个这个错；你在项目代码里用到了 qt 吗。

**Comment by xunxuntu** [comment]
可以在，在1050显卡上可以跑起来的，谢谢。😎😎😎😎😎😎

**Comment by ssunchaser** [comment]
好的好的，能成功运行就好。
